apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-prod.yml --volumes hostPath
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: php
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: php
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-prod.yml --volumes hostPath
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: php
    spec:
      containers:
      - image: gcr.io/unifavela-moodle/moodledocker_php@sha256:8d2618e579c035716be53e966961f167da7aa92ca65b7151e59ce65a0e984bb9
        imagePullPolicy: ""
        name: php
        resources: {}
        volumeMounts:
        - mountPath: /var/www/moodle
          name: php-hostpath0
        - mountPath: /usr/local/etc/php/php.ini
          name: php-hostpath1
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /home/felipecurvelo/moodle
        name: php-hostpath0
      - hostPath:
          path: /home/felipecurvelo/moodledocker/php.ini
        name: php-hostpath1
status: {}
